version: '3'
services:
  frontend:
    image: netkovjordan/my-reactfrontend-app:latest
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    image: netkovjordan/my-springboot-app:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/book_shop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=EscanorSama
    depends_on:
      - database
  database:
    image: netkovjordan/my-postgredb:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=book_shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=EscanorSama
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
